name: swayze
description: A set of widgets and controllers to display very large tables on flutter apps.
version: 1.2.0
repository: https://github.com/rows/swayze
issue_tracker: https://github.com/rows/swayze/issues
homepage: https://github.com/rows/swayze

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sticky_header: ^0.6.0
  memoize: ^3.0.0
  built_collection: ^5.0.0
  uuid: ^3.0.3
  cached_value: ^0.2.0
  path_drawing: ^1.0.0
  swayze_math: ^1.1.0
  meta: ^1.7.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  rows_lint: 0.1.1
  test: ^1.16.8
  mocktail: ^0.2.0
  build_runner: ^2.0.1
  dartdoc: ^2.0.0

flutter:
